services:
  hsm-be-core-docs:
    image: hsm-be-core-docs:latest
    build:
      context: ../../../../../hsm-be-core-docs
      dockerfile: Dockerfile.dev
    container_name: hsm-be-core-docs
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../hsm-be-core-docs:/app
      - /app/node_modules
    env_file:
      - ../../../../.env
    environment:
      SECRET_PATH: /be/core/docs
      HSM_BE_CORE_STORAGE_HOST: hsm-be-core-storage
      HSM_BE_CORE_STORAGE_PORT: 9000
      HSM_BE_CORE_STORAGE_ACCESS_KEY: admin
      HSM_BE_CORE_STORAGE_SECRET_KEY: password
      HSM_BE_CORE_STORAGE_BUCKET: hsm-be-core-docs
    restart: unless-stopped
    depends_on:
      - hsm-be-core-storage
      - hsm-be-core-gateway
      - hsm-be-extras-browser
      
