services:
  hsm-be-core-docs:
    image: hsm-be-core-docs:latest
    build:
      context: ../../../../../hsm-be-core-docs
      dockerfile: Dockerfile.dev
    container_name: hsm-be-core-docs
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../hsm-be-core-docs:/app
      - /app/node_modules
    env_file:
      - ../../../../.env
    environment:
      SECRET_PATH: /be/core/docs
      LD_LIBRARY_PATH: /usr/lib/oracle/12.1/client64/lib
    restart: unless-stopped
    depends_on:
      - hsm-be-core-storage
      - hsm-be-core-gateway
      - hsm-be-extras-browser
      
