name: hsm

networks:
  hsm-backend-network:
    name: hsm-backend-network
    driver: bridge

services:
  hsm-fe-web:
    extends:
      file: ./services/fe/web/docker-compose.dev.yml
      service: hsm-fe-web
  hsm-be-core-gateway:
    extends:
      file: ./services/be/core/gateway/docker-compose.dev.yml
      service: hsm-be-core-gateway
  hsm-be-core-storage:
    extends:
      file: ./services/be/core/storage/docker-compose.dev.yml
      service: hsm-be-core-storage
  hsm-be-core-auth:
    extends:
      file: ./services/be/core/auth/docker-compose.dev.yml
      service: hsm-be-core-auth
  hsm-be-core-common:
    extends:
      file: ./services/be/core/common/docker-compose.dev.yml
      service: hsm-be-core-common
  hsm-be-core-coms:
    extends:
      file: ./services/be/core/coms/docker-compose.dev.yml
      service: hsm-be-core-coms
  hsm-be-core-users:
    extends:
      file: ./services/be/core/users/docker-compose.dev.yml
      service: hsm-be-core-users
  hsm-be-core-docs:
    extends:
      file: ./services/be/core/docs/docker-compose.dev.yml
      service: hsm-be-core-docs
  hsm-be-has-cob-gdp-transaccion:
    extends:
      file: ./services/be/has/cob/gdp/transaccion/docker-compose.dev.yml
      service: hsm-be-has-cob-gdp-transaccion
  hsm-be-has-gaa-gth-gsr-postulantes:
    extends:
      file: ./services/be/has/gaa/gth/gsr/postulantes/docker-compose.dev.yml
      service: hsm-be-has-gaa-gth-gsr-postulantes
  hsm-be-has-gaa-gth-gsr-trabajos:
    extends:
      file: ./services/be/has/gaa/gth/gsr/trabajo/docker-compose.dev.yml
      service: hsm-be-has-gaa-gth-gsr-trabajos

  hsm-be-extras-browser:
    extends:
      file: ./services/be/extras/browser/docker-compose.dev.yml
      service: hsm-be-extras-browser

  hsm-be-his-paciente:
    extends:
      file: ./services/be/his/paciente/docker-compose.dev.yml
      service: hsm-be-his-paciente

  # hsm-be-has-gaa-gth-gdn-empleados:
  #   extends:
  #     file: ./services/be/has/gaa/gth/gdn/empleados/docker-compose.dev.yml
  #     service: hsm-be-has-gaa-gth-gdn-empleados

  # hsm-be-has-gaa-gth-gdn-empresas:
  #   extends:
  #     file: ./services/be/has/gaa/gth/gdn/empresas/docker-compose.dev.yml
  #     service: hsm-be-has-gaa-gth-gdn-empresas

  # hsm-be-has-gaa-gth-gdn-asistencias:
  #   extends:
  #     file: ./services/be/has/gaa/gth/gdn/asistencias/docker-compose.dev.yml
  #     service: hsm-be-has-gaa-gth-gdn-asistencias

  # hsm-be-has-gaa-gth-gdn-deducciones:
  #   extends:
  #     file: ./services/be/has/gaa/gth/gdn/deducciones/docker-compose.dev.yml
  #     service: hsm-be-has-gaa-gth-gdn-deducciones

  # hsm-be-has-gaa-gth-gdn-beneficios:
  #   extends:
  #     file: ./services/be/has/gaa/gth/gdn/beneficios/docker-compose.dev.yml
  #     service: hsm-be-has-gaa-gth-gdn-beneficios

  # hsm-be-has-gaa-gth-gdn-liquidaciones:
  #   extends:
  #     file: ./services/be/has/gaa/gth/gdn/liquidaciones/docker-compose.dev.yml
  #     service: hsm-be-has-gaa-gth-gdn-liquidaciones
