name: HSM-BACKEND

networks:
  HSM-BACKEND-NETWORK:
    driver: bridge

services:

  # FRONTEND WEB
  HSM-FE-WEB:
    image: hsm-fe-web:latest
    build:
      context: ../HSM-FE-WEB
      dockerfile: Dockerfile
    container_name: HSM-FE-WEB
    ports:
      - $HSM_FE_WEB_PORT:4200
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-FE-WEB:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-fe-web.env
    restart: unless-stopped

  # Gateway Service
  HSM-BE-CORE-GATEWAY:
    image: hsm-be-core-gateway:latest
    build:
      context: ../HSM-BE-CORE-GATEWAY
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-GATEWAY
    ports:
      - $HSM_BE_CORE_GATEWAY_PORT:$HSM_BE_CORE_GATEWAY_PORT
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-CORE-GATEWAY:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-core-gateway.env
    restart: unless-stopped

  # Auth Service
  HSM-BE-CORE-AUTH:
    image: hsm-be-core-auth:latest
    build:
      context: ../HSM-BE-CORE-AUTH
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-AUTH
    ports:
      - $HSM_BE_CORE_AUTH_WS_PORT:$HSM_BE_CORE_AUTH_WS_PORT
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-CORE-AUTH:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-core-auth.env
    restart: unless-stopped

  # Communications Service
  HSM-BE-CORE-COMS:
    image: hsm-be-core-coms:latest
    build:
      context: ../HSM-BE-CORE-COMS
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-COMS
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-CORE-COMS:/app
      - /app/node_modules
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./.env
      - ./envs/hsm-be-core-coms.env
    restart: unless-stopped

  # Common Service
  HSM-BE-CORE-COMMON:
    image: hsm-be-core-common:latest
    build:
      context: ../HSM-BE-CORE-COMMON
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-COMMON
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-CORE-COMMON:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-core-common.env
    restart: unless-stopped

  # Users Service
  HSM-BE-CORE-USERS:
    image: hsm-be-core-users:latest
    build:
      context: ../HSM-BE-CORE-USERS
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-USERS
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-CORE-USERS:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-core-users.env
    restart: unless-stopped

  # Docs Service
  HSM-BE-CORE-DOCS:
    image: hsm-be-core-docs:latest
    build:
      context: ../HSM-BE-CORE-DOCS
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-DOCS
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-CORE-DOCS:/app # Volumen para código fuente
      - "C:/Users/HBAQUE/Desktop/Nueva carpeta/Archivos:/app/uploads" # Volumen para archivos persistentes
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-core-docs.env
    restart: unless-stopped

  # Postulantes Service
  HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES:
    image: hsm-be-has-gaa-gth-gsr-postulantes:latest
    build:
      context: ../HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES
      dockerfile: Dockerfile
    container_name: HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-has-gaa-gth-gsr-postulantes.env
    restart: unless-stopped

  # Trabajo Service
  HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS:
    image: hsm-be-has-gaa-gth-gsr-trabajos:latest
    build:
      context: ../HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS
      dockerfile: Dockerfile
    container_name: HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS
    networks:
      - HSM-BACKEND-NETWORK
    volumes:
      - ../HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/hsm-be-has-gaa-gth-gsr-trabajos.env
    restart: unless-stopped
