name: HSM-BACKEND

networks:
  HSM-BACKEND-NETWORK:
    driver: bridge
    ipam:
      config:
        - subnet: $HSM_DOCKER_SUBNET

services:

  # FRONTEND WEB
  HSM-FE-WEB:
    image: hsm-fe-web:latest
    build:
      context: ../HSM-FE-WEB
      dockerfile: Dockerfile
    container_name: HSM-FE-WEB
    env_file:
      - ./.env
      - ./envs/hsm-fe-web.env
    ports:
      - ${HSM_FE_WEB_PORT}:4200
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_FE_WEB_HOST
    volumes:
      - ../HSM-FE-WEB:/app
      - /app/node_modules
    restart: unless-stopped

  # Gateway Service
  HSM-BE-CORE-GATEWAY:
    image: hsm-be-core-gateway:latest
    build:
      context: ../HSM-BE-CORE-GATEWAY
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-GATEWAY
    env_file:
      - ./.env
      - ./envs/hsm-be-core-gateway.env
    ports:
      - ${HSM_BE_CORE_GATEWAY_PORT}:${HSM_BE_CORE_GATEWAY_PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_CORE_GATEWAY_HOST
    volumes:
      - ../HSM-BE-CORE-GATEWAY:/app
      - /app/node_modules
    restart: unless-stopped

  # Auth Service
  HSM-BE-CORE-AUTH:
    image: hsm-be-core-auth:latest
    build:
      context: ../HSM-BE-CORE-AUTH
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-AUTH
    env_file:
      - ./.env
      - ./envs/hsm-be-core-auth.env
    ports:
      - ${HSM_BE_CORE_AUTH_WS_PORT}:${HSM_BE_CORE_AUTH_WS_PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_CORE_AUTH_HOST
    volumes:
      - ../HSM-BE-CORE-AUTH:/app
      - /app/node_modules
    restart: unless-stopped

  # Communications Service
  HSM-BE-CORE-COMS:
    image: hsm-be-core-coms:latest
    build:
      context: ../HSM-BE-CORE-COMS
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-COMS
    env_file:
      - ./.env
      - ./envs/hsm-be-core-coms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_CORE_COMS_HOST
    volumes:
      - ../HSM-BE-CORE-COMS:/app
      - /app/node_modules
    restart: unless-stopped

  # Common Service
  HSM-BE-CORE-COMMON:
    image: hsm-be-core-common:latest
    build:
      context: ../HSM-BE-CORE-COMMON
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-COMMON
    env_file:
      - ./.env
      - ./envs/hsm-be-core-common.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_CORE_COMMON_HOST
    volumes:
      - ../HSM-BE-CORE-COMMON:/app
      - /app/node_modules
    restart: unless-stopped

  # Users Service
  HSM-BE-CORE-USERS:
    image: hsm-be-core-users:latest
    build:
      context: ../HSM-BE-CORE-USERS
      dockerfile: Dockerfile
    container_name: HSM-BE-CORE-USERS
    env_file:
      - ./.env
      - ./envs/hsm-be-core-users.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_CORE_USERS_HOST
    volumes:
      - ../HSM-BE-CORE-USERS:/app
      - /app/node_modules
    restart: unless-stopped

  # Postulantes Service
  HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES:
    image: hsm-be-has-gaa-gth-gsr-postulantes:latest
    build:
      context: ../HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES
      dockerfile: Dockerfile
    container_name: HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES
    env_file:
      - ./.env
      - ./envs/hsm-be-has-gaa-gth-gsr-postulantes.env
    ports:
      - ${HSM_BE_HAS_GAA_GTH_GSR_POSTULANTES_PORT}:${HSM_BE_HAS_GAA_GTH_GSR_POSTULANTES_PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_HAS_GAA_GTH_GSR_POSTULANTES_HOST
    volumes:
      - ../HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES:/app
      - /app/node_modules
    restart: unless-stopped

  # Trabajo Service
  HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS:
    image: hsm-be-has-gaa-gth-gsr-trabajos:latest
    build:
      context: ../HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS
      dockerfile: Dockerfile
    container_name: HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS
    env_file:
      - ./.env
      - ./envs/hsm-be-has-gaa-gth-gsr-trabajos.env
    ports:
      - ${HSM_BE_HAS_GAA_GTH_GSR_TRABAJOS_PORT}:${HSM_BE_HAS_GAA_GTH_GSR_TRABAJOS_PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM_BE_HAS_GAA_GTH_GSR_TRABAJOS_HOST
    volumes:
      - ../HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS:/app
      - /app/node_modules
    restart: unless-stopped

  
