name: HSM-BACKEND

networks:
  HSM-BACKEND-NETWORK:
    driver: bridge
    ipam:
      config:
        - subnet: $DOCKER_SUBNET

services:

  # Gateway Service
  HSM-CORE-GATEWAY-MS:
    image: hsm-core-gateway-ms:latest
    build:
      context: ../HSM-CORE-GATEWAY-MS
      dockerfile: Dockerfile
    container_name: HSM-CORE-GATEWAY-MS
    env_file:
      - ./.env
      - ./envs/hsm-core-gateway-ms.env
    ports:
      - ${GATEWAY_MICROSERVICE_PORT}:${GATEWAY_MICROSERVICE_PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $GATEWAY_MICROSERVICE_HOST
    volumes:
      - ../HSM-CORE-GATEWAY-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Auth Service
  HSM-CORE-AUTH-MS:
    image: hsm-core-auth-ms:latest
    build:
      context: ../HSM-CORE-AUTH-MS
      dockerfile: Dockerfile
    container_name: HSM-CORE-AUTH-MS
    env_file:
      - ./.env
      - ./envs/hsm-core-auth-ms.env
    ports:
      - ${AUTH_WEBSOCKET_MICROSERVICE_PORT}:${AUTH_WEBSOCKET_MICROSERVICE_PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $AUTH_MICROSERVICE_HOST
    volumes:
      - ../HSM-CORE-AUTH-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Communications Service
  HSM-CORE-COMS-MS:
    image: hsm-core-coms-ms:latest
    build:
      context: ../HSM-CORE-COMS-MS
      dockerfile: Dockerfile
    container_name: HSM-CORE-COMS-MS
    env_file:
      - ./.env
      - ./envs/hsm-core-coms-ms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $COMS_MICROSERVICE_HOST
    volumes:
      - ../HSM-CORE-COMS-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Common Service
  HSM-CORE-COMMON-MS:
    image: hsm-core-common-ms:latest
    build:
      context: ../HSM-CORE-COMMON-MS
      dockerfile: Dockerfile
    container_name: HSM-CORE-COMMON-MS
    env_file:
      - ./.env
      - ./envs/hsm-core-common-ms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $COMMON_MICROSERVICE_HOST
    volumes:
      - ../HSM-CORE-COMMON-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Postulantes Service
  HSM-HAS-GAA-GTH-GSR-POSTULANTES-MS:
    image: hsm-has-gaa-gth-gsr-postulantes-ms:latest
    build:
      context: ../HSM-HAS-GAA-GTH-GSR-POSTULANTES-MS
      dockerfile: Dockerfile
    container_name: HSM-HAS-GAA-GTH-GSR-POSTULANTES-MS
    env_file:
      - ./.env
      - ./envs/hsm-has-gaa-gth-gsr-postulantes-ms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $POSTULANTES_MICROSERVICE_HOST
    volumes:
      - ../HSM-HAS-GAA-GTH-GSR-POSTULANTES-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Trabajo Service
  HSM-HAS-GAA-GTH-GSR-TRABAJOS-MS:
    image: hsm-has-gaa-gth-gsr-trabajos-ms:latest
    build:
      context: ../HSM-HAS-GAA-GTH-GSR-TRABAJOS-MS
      dockerfile: Dockerfile
    container_name: HSM-HAS-GAA-GTH-GSR-TRABAJOS-MS
    env_file:
      - ./.env
      - ./envs/hsm-has-gaa-gth-gsr-trabajos-ms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $TRABAJO_MICROSERVICE_HOST
    volumes:
      - ../HSM-HAS-GAA-GTH-GSR-TRABAJOS-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Users Service
  HSM-CORE-USERS-MS:
    image: hsm-core-users-ms:latest
    build:
      context: ../HSM-CORE-USERS-MS
      dockerfile: Dockerfile
    container_name: HSM-CORE-USERS-MS
    env_file:
      - ./.env
      - ./envs/hsm-core-users-ms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $USERS_MICROSERVICE_HOST
    volumes:
      - ../HSM-CORE-USERS-MS:/app
      - /app/node_modules
    restart: unless-stopped
