name: backend

services:

  #Gateway service
  HSM-BE-GATEWAY-MS:
    image: hsm-be-gateway-ms:latest
    build:
      context: ../HSM-BE-GATEWAY-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-GATEWAY-MS
    ports:
      - $GATEWAY_MICROSERVICE_PORT:$GATEWAY_MICROSERVICE_PORT
    networks:
      app_network:
        ipv4_address: $GATEWAY_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/gateway.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-GATEWAY-MS:/app
      - /app/node_modules
    restart: unless-stopped

  #Auth service
  HSM-BE-AUTH-MS:
    image: hsm-be-auth-ms:latest
    build:
      context: ../HSM-BE-AUTH-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-AUTH-MS
    ports:
      - $AUTH_MICROSERVICE_PORT:$AUTH_MICROSERVICE_PORT
    networks:
      app_network:
        ipv4_address: $AUTH_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/auth.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-AUTH-MS:/app
      - /app/node_modules
    restart: unless-stopped

  #Coms service
  HSM-BE-COMS-MS:
    image: hsm-be-coms-ms:latest
    build:
      context: ../HSM-BE-COMS-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-COMS-MS
    networks:
      app_network:
        ipv4_address: $COMS_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/coms.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-COMS-MS:/app
      - /app/node_modules
    restart: unless-stopped

  #Coms service
  HSM-BE-COMMON-MS:
    image: hsm-be-common-ms:latest
    build:
      context: ../HSM-BE-COMMON-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-COMMON-MS
    networks:
      app_network:
        ipv4_address: $COMMON_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/common.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-COMMON-MS:/app
      - /app/node_modules
    restart: unless-stopped

  #Examenes service
  HSM-BE-EXAMENES-MS:
    image: hsm-be-examenes-ms:latest
    build:
      context: ../HSM-BE-EXAMENES-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-EXAMENES-MS
    networks:
      app_network:
        ipv4_address: $EXAMENES_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/examenes.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-EXAMENES-MS:/app
      - /app/node_modules
    restart: unless-stopped

  #Facturacion service
  HSM-BE-FACTURACION-MS:
    image: hsm-be-facturacion-ms:latest
    build:
      context: ../HSM-BE-FACTURACION-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-FACTURACION-MS
    networks:
      app_network:
        ipv4_address: $FACTURACION_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/facturacion.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-FACTURACION-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Farmacia Service
  HSM-BE-FARMACIA-MS:
    image: hsm-be-farmacia-ms:latest
    build:
      context: ../HSM-BE-FARMACIA-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-FARMACIA-MS
    networks:
      app_network:
        ipv4_address: $FARMACIA_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/farmacia.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-FARMACIA-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Hospitalizacion Service
  HSM-BE-HOSPITALIZACION-MS:
    image: hsm-be-hospitalizacion-ms:latest
    build:
      context: ../HSM-BE-HOSPITALIZACION-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-HOSPITALIZACION-MS
    networks:
      app_network:
        ipv4_address: $HOSPITALIZACION_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/hospitalizacion.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-HOSPITALIZACION-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Medicos Service
  HSM-BE-MEDICOS-MS:
    image: hsm-be-medicos-ms:latest
    build:
      context: ../HSM-BE-MEDICOS-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-MEDICOS-MS
    networks:
      app_network:
        ipv4_address: $MEDICOS_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/medicos.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-MEDICOS-MS:/app
      - /app/node_modules
    restart: unless-stopped

  #Pacientes service
  HSM-BE-PACIENTES-MS:
    image: hsm-be-pacientes-ms:latest
    build:
      context: ../HSM-BE-PACIENTES-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-PACIENTES-MS
    networks:
      app_network:
        ipv4_address: $PACIENTES_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/pacientes.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-PACIENTES-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Personal Service
  HSM-BE-PERSONAL-MS:
    image: hsm-be-personal-ms:latest
    build:
      context: ../HSM-BE-PERSONAL-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-PERSONAL-MS
    networks:
      app_network:
        ipv4_address: $PERSONAL_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/personal.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-PERSONAL-MS:/app
      - /app/node_modules
    restart: unless-stopped

  # Users Service
  HSM-BE-USERS-MS:
    image: hsm-be-users-ms:latest
    build:
      context: ../HSM-BE-USERS-MS
      dockerfile: Dockerfile
    container_name: HSM-BE-USERS-MS
    networks:
      app_network:
        ipv4_address: $USERS_MICROSERVICE_HOST
    env_file:
      - ./envs/global.env
      - ./envs/users.env
    environment:
      - ORACLE_CLIENT_PATH=/usr/lib/oracle/12.1/client64/lib
      - LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
    volumes:
      - ../HSM-BE-USERS-MS:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: $DOCKER_SUBNET
