name: hsm

networks:
  hsm-backend-network:
    driver: bridge

services:

  # FRONTEND WEB
  hsm-fe-web:
    image: ${hsm_fe_web}:latest
    build:
      context: ../${hsm_fe_web}
      dockerfile: Dockerfile
    container_name: ${hsm_fe_web}
    ports:
      - ${hsm_fe_web_port}:4200
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_fe_web}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_fe_web}.env
    restart: unless-stopped

  # Gateway Service
  hsm-be-core-gateway:
    image: ${hsm_be_core_gateway}:latest
    build:
      context: ../${hsm_be_core_gateway}
      dockerfile: Dockerfile
    container_name: ${hsm_be_core_gateway}
    ports:
      - ${hsm_be_core_gateway_port}:${hsm_be_core_gateway_port}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_core_gateway}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_gateway}.env
    restart: unless-stopped

  # Auth Service
  hsm-be-core-auth:
    image: ${hsm_be_core_auth}:latest
    build:
      context: ../${hsm_be_core_auth}
      dockerfile: Dockerfile
    container_name: ${hsm_be_core_auth}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_core_auth}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_auth}.env
    restart: unless-stopped

  # Communications Service
  hsm-be-core-coms:
    image: ${hsm_be_core_coms}:latest
    build:
      context: ../${hsm_be_core_coms}
      dockerfile: Dockerfile
    container_name: ${hsm_be_core_coms}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_core_coms}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_coms}.env
    restart: unless-stopped

  # Common Service
  hsm-be-core-common:
    image: ${hsm_be_core_common}:latest
    build:
      context: ../${hsm_be_core_common}
      dockerfile: Dockerfile
    container_name: ${hsm_be_core_common}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_core_common}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_common}.env
    restart: unless-stopped

  # Users Service
  hsm-be-core-users:
    image: ${hsm_be_core_users}:latest
    build:
      context: ../${hsm_be_core_users}
      dockerfile: Dockerfile
    container_name: ${hsm_be_core_users}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_core_users}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_users}.env
    restart: unless-stopped

  # Docs Service
  hsm-be-core-docs:
    image: ${hsm_be_core_docs}:latest
    build:
      context: ../${hsm_be_core_docs}
      dockerfile: Dockerfile
    container_name: ${hsm_be_core_docs}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_core_docs}:/app
      - "C:/Users/HBAQUE/Desktop/Nueva carpeta/Archivos:/app/uploads"
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_docs}.env
    restart: unless-stopped

  # Postulantes Service
  hsm-be-has-gaa-gth-gsr-postulantes:
    image: ${hsm_be_has_gaa_gth_gsr_postulantes}:latest
    build:
      context: ../${hsm_be_has_gaa_gth_gsr_postulantes}
      dockerfile: Dockerfile
    container_name: ${hsm_be_has_gaa_gth_gsr_postulantes}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_has_gaa_gth_gsr_postulantes}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_gaa_gth_gsr_postulantes}.env
    restart: unless-stopped

  # Trabajo Service
  hsm-be-has-gaa-gth-gsr-trabajos:
    image: ${hsm_be_has_gaa_gth_gsr_trabajos}:latest
    build:
      context: ../${hsm_be_has_gaa_gth_gsr_trabajos}
      dockerfile: Dockerfile
    container_name: ${hsm_be_has_gaa_gth_gsr_trabajos}
    networks:
      - hsm-backend-network
    volumes:
      - ../${hsm_be_has_gaa_gth_gsr_trabajos}:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_gaa_gth_gsr_trabajos}.env
    restart: unless-stopped
