name: hsm

networks:
  hsm-backend-network:
    driver: bridge

services:

  # FRONTEND WEB
  hsm-fe-web:
    image: ghcr.io/hsm-sanosoft/${hsm_fe_web}:latest
    container_name: ${hsm_fe_web}
    ports:
      - ${hsm_fe_web_port}:4200
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_fe_web}.env
    restart: unless-stopped

  # Gateway Service
  hsm-be-core-gateway:
    image: ghcr.io/hsm-sanosoft/${hsm_be_core_gateway}:latest
    container_name: ${hsm_be_core_gateway}
    ports:
      - ${hsm_be_core_gateway_port}:${hsm_be_core_gateway_port}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_gateway}.env
    restart: unless-stopped

  # Auth Service
  hsm-be-core-auth:
    image: ghcr.io/hsm-sanosoft/${hsm_be_core_auth}:latest
    container_name: ${hsm_be_core_auth}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_auth}.env
    restart: unless-stopped

  # Communications Service
  hsm-be-core-coms:
    image: ghcr.io/hsm-sanosoft/${hsm_be_core_coms}:latest
    container_name: ${hsm_be_core_coms}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_coms}.env
    restart: unless-stopped

  # Common Service
  hsm-be-core-common:
    image: ghcr.io/hsm-sanosoft/${hsm_be_core_common}:latest
    container_name: ${hsm_be_core_common}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_common}.env
    restart: unless-stopped

  # Users Service
  hsm-be-core-users:
    image: ghcr.io/hsm-sanosoft/${hsm_be_core_users}:latest
    container_name: ${hsm_be_core_users}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_users}.env
    restart: unless-stopped

  # Docs Service
  hsm-be-core-docs:
    image: ghcr.io/hsm-sanosoft/${hsm_be_core_docs}:latest
    container_name: ${hsm_be_core_docs}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_core_docs}.env
    restart: unless-stopped

  # Postulantes Service
  hsm-be-has-gaa-gth-gsr-postulantes:
    image: ghcr.io/hsm-sanosoft/${hsm_be_has_gaa_gth_gsr_postulantes}:latest
    container_name: ${hsm_be_has_gaa_gth_gsr_postulantes}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_gaa_gth_gsr_postulantes}.env
    restart: unless-stopped

  # Trabajo Service
  hsm-be-has-gaa-gth-gsr-trabajos:
    image: ghcr.io/hsm-sanosoft/${hsm_be_has_gaa_gth_gsr_trabajos}:latest
    container_name: ${hsm_be_has_gaa_gth_gsr_trabajos}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_gaa_gth_gsr_trabajos}.env
    restart: unless-stopped

  # Transaccion Service
  hsm-be-has-cob-gdp-transaccion:
    image: ghcr.io/hsm-sanosoft/${hsm_be_has_cob_gdp_transaccion}:latest
    container_name: ${hsm_be_has_cob_gdp_transaccion}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_cob_gdp_transaccion}.env
    restart: unless-stopped

  # Compensacion Service
  hsm-be-has-cob-gdp-compensacion:
    image: ghcr.io/hsm-sanosoft/${hsm_be_has_cob_gdp_compensacion}:latest
    container_name: ${hsm_be_has_cob_gdp_compensacion}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_cob_gdp_compensacion}.env
    restart: unless-stopped

  # Recaudo Service
  hsm-be-has-cob-gdp-recaudo:
    image: ghcr.io/hsm-sanosoft/${hsm_be_has_cob_gdp_recaudo}:latest
    container_name: ${hsm_be_has_cob_gdp_recaudo}
    networks:
      - hsm-backend-network
    env_file:
      - ./.env
      - ./envs/${hsm_be_has_cob_gdp_recaudo}.env
    restart: unless-stopped
