name: HSM-BACKEND

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: $DOCKER_SUBNET

services:
  #FRONTED WEB
  HSM-FE-WEB:
    image: ghcr.io/hsm-sanosoft/hsm-fe-web:latest
    container_name: HSM-FE-WEB
    ports:
      - $HSM_FE_WEB_PORT:4200
    networks:
      app_network:
        ipv4_address: $HSM_FE_WEB_HOST
    env_file:
      - ./.env
      - ./envs/hsm-fe-web.env
    restart: unless-stopped

  #Gateway service
  HSM-BE-CORE-GATEWAY:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-gateway:latest
    container_name: HSM-BE-CORE-GATEWAY
    ports:
      - $HSM_BE_CORE_GATEWAY_PORT:$HSM_BE_CORE_GATEWAY_PORT
    networks:
      app_network:
        ipv4_address: $HSM_BE_CORE_GATEWAY_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-core-gateway.env
    restart: unless-stopped

  #Auth service
  HSM-BE-CORE-AUTH:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-auth:latest
    container_name: HSM-BE-CORE-AUTH
    ports:
      - $HSM_BE_CORE_AUTH_WS_PORT:$HSM_BE_CORE_AUTH_WS_PORT
    networks:
      app_network:
        ipv4_address: $HSM_BE_CORE_AUTH_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-core-auth.env
    restart: unless-stopped

  #Coms service
  HSM-BE-CORE-COMS:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-coms:latest
    container_name: HSM-BE-CORE-COMS
    networks:
      app_network:
        ipv4_address: $HSM_BE_CORE_COMS_HOST
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./envs/global.env
      - ./envs/coms.env
    restart: unless-stopped
    
  #Coms Email service
  HSM-BE-CORE-COMS-EMAIL:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-coms-email:latest
    container_name: HSM-BE-CORE-COMS-EMAIL
    ports:
      - $HSM_BE_CORE_COMS_EMAIL_PORT:$HSM_BE_CORE_COMS_EMAIL_PORT
    networks:
      app_network:
        ipv4_address: $HSM_BE_CORE_COMS_EMAIL_HOST
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./.env
      - ./envs/hsm-be-core-coms-email.env
    restart: unless-stopped

  #COMMON service
  HSM-BE-CORE-COMMON:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-common:latest
    container_name: HSM-BE-CORE-COMMON
    networks:
      app_network:
        ipv4_address: $HSM_BE_CORE_COMMON_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-core-common.env
    restart: unless-stopped

 # Users Service
  HSM-BE-CORE-USERS:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-users:latest
    container_name: HSM-BE-CORE-USERS
    networks:
      app_network:
        ipv4_address: $HSM_BE_CORE_USERS_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-core-users.env
    restart: unless-stopped
    
  #DOCS service
  HSM-BE-CORE-DOCS:
    image: ghcr.io/hsm-sanosoft/hsm-be-core-docs:latest
    container_name: HSM-BE-CORE-DOCS
    networks:
      app_network:
        ipv4_address:  $HSM_BE_CORE_DOCS_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-core-docs.env
    restart: unless-stopped

  
  # Postulantes Service
  HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES:
    image: ghcr.io/hsm-sanosoft/hsm-be-has-gaa-gth-gsr-postulantes:latest
    container_name: HSM-BE-HAS-GAA-GTH-GSR-POSTULANTES
    networks:
      app_network:
        ipv4_address: $HSM_BE_HAS_GAA_GTH_GSR_POSTULANTES_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-has-gaa-gth-gsr-postulantes.env
    restart: unless-stopped


  # Trabajo Service
  HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS:
    image: ghcr.io/hsm-sanosoft/hsm-be-has-gaa-gth-gsr-trabajos:latest
    container_name: HSM-BE-HAS-GAA-GTH-GSR-TRABAJOS
    networks:
      app_network:
        ipv4_address: $HSM_BE_HAS_GAA_GTH_GSR_TRABAJOS_HOST
    env_file:
      - ./.env
      - ./envs/hsm-be-has-gaa-gth-gsr-trabajos.env
    restart: unless-stopped
