name: HSM-BACKEND

networks:
  HSM-BACKEND-NETWORK:
    driver: bridge
    ipam:
      config:
        - subnet: $HSM-DOCKER-SUBNET

services:

  # Gateway Service
  HSM-CORE-GATEWAY:
    image: hsm-core-gateway:latest
    build:
      context: ../HSM-CORE-GATEWAY
      dockerfile: Dockerfile
    container_name: HSM-CORE-GATEWAY
    env_file:
      - ./.env
      - ./envs/hsm-core-gateway.env
    ports:
      - ${HSM-CORE-GATEWAY-PORT}:${HSM-CORE-GATEWAY-PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-CORE-GATEWAY-HOST
    volumes:
      - ../HSM-CORE-GATEWAY:/app
      - /app/node_modules
    restart: unless-stopped

  # Auth Service
  HSM-CORE-AUTH:
    image: hsm-core-auth:latest
    build:
      context: ../HSM-CORE-AUTH
      dockerfile: Dockerfile
    container_name: HSM-CORE-AUTH
    env_file:
      - ./.env
      - ./envs/hsm-core-auth.env
    ports:
      - ${HSM-CORE-AUTH-WS-PORT}:${HSM-CORE-AUTH-WS-PORT}
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-CORE-AUTH-HOST
    volumes:
      - ../HSM-CORE-AUTH:/app
      - /app/node_modules
    restart: unless-stopped

  # Communications Service
  HSM-CORE-COMS:
    image: hsm-core-coms:latest
    build:
      context: ../HSM-CORE-COMS
      dockerfile: Dockerfile
    container_name: HSM-CORE-COMS
    env_file:
      - ./.env
      - ./envs/hsm-core-coms.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-CORE-COMS-HOST
    volumes:
      - ../HSM-CORE-COMS:/app
      - /app/node_modules
    restart: unless-stopped

  # Common Service
  HSM-CORE-COMMON:
    image: hsm-core-common:latest
    build:
      context: ../HSM-CORE-COMMON
      dockerfile: Dockerfile
    container_name: HSM-CORE-COMMON
    env_file:
      - ./.env
      - ./envs/hsm-core-common.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-CORE-COMMON-HOST
    volumes:
      - ../HSM-CORE-COMMON:/app
      - /app/node_modules
    restart: unless-stopped

  # Postulantes Service
  HSM-HAS-GAA-GTH-GSR-POSTULANTES:
    image: hsm-has-gaa-gth-gsr-postulantes:latest
    build:
      context: ../HSM-HAS-GAA-GTH-GSR-POSTULANTES
      dockerfile: Dockerfile
    container_name: HSM-HAS-GAA-GTH-GSR-POSTULANTES
    env_file:
      - ./.env
      - ./envs/hsm-has-gaa-gth-gsr-postulantes.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-HAS-GAA-GTH-GSR-POSTULANTES-HOST
    volumes:
      - ../HSM-HAS-GAA-GTH-GSR-POSTULANTES:/app
      - /app/node_modules
    restart: unless-stopped

  # Trabajo Service
  HSM-HAS-GAA-GTH-GSR-TRABAJOS:
    image: hsm-has-gaa-gth-gsr-trabajos:latest
    build:
      context: ../HSM-HAS-GAA-GTH-GSR-TRABAJOS
      dockerfile: Dockerfile
    container_name: HSM-HAS-GAA-GTH-GSR-TRABAJOS
    env_file:
      - ./.env
      - ./envs/hsm-has-gaa-gth-gsr-trabajos.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-HAS-GAA-GTH-GSR-TRABAJOS-HOST
    volumes:
      - ../HSM-HAS-GAA-GTH-GSR-TRABAJOS:/app
      - /app/node_modules
    restart: unless-stopped

  # Users Service
  HSM-CORE-USERS:
    image: hsm-core-users:latest
    build:
      context: ../HSM-CORE-USERS
      dockerfile: Dockerfile
    container_name: HSM-CORE-USERS
    env_file:
      - ./.env
      - ./envs/hsm-core-users.env
    networks:
      HSM-BACKEND-NETWORK:
        ipv4_address: $HSM-CORE-USERS-HOST
    volumes:
      - ../HSM-CORE-USERS:/app
      - /app/node_modules
    restart: unless-stopped
