name: CI/CD for Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rsantamaria01
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and Push with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/hsm-sanosoft/${{vars.MICROSERVICE_NAME}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rsantamaria01
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Pull and Deploy Microservices
        run: |
          echo "Navigating to directory: ${{secrets.PATH_DOCKER_COMPOSE}}"
          cd ${{secrets.PATH_DOCKER_COMPOSE}}
          
          echo "Pulling the latest image for ${{vars.MICROSERVICE_NAME}}..."
          docker pull ghcr.io/hsm-sanosoft/${{vars.MICROSERVICE_NAME}}:latest

          echo "Restarting ${{vars.MICROSERVICE_NAME}} container..."
          docker-compose -f docker-compose.prod.yml up -d --no-deps ${{vars.MICROSERVICE_NAME}}
