  services:
    hsm-be-core-storage:
      container_name: hsm-be-core-storage
      image: hsm-be-core-storage:latest
      build:
        context: ./
        dockerfile: Dockerfile.dev
      networks:
        - hsm-backend-network
      ports:
        - "9000:9000"
        - "9001:9001"
      env_file:
      - ../../../../.env
      environment:
        SECRET_PATH: /be/core/storage
      restart: unless-stopped