services:
  hsm-be-core-gateway:
    image: hsm-be-core-gateway:latest
    build:
      context: ../../../../../hsm-be-core-gateway
      dockerfile: Dockerfile.dev
    container_name: hsm-be-core-gateway
    ports:
      - 3000:3000
    networks:
      - hsm-backend-network
    volumes:
      - ../../../../../hsm-be-core-gateway:/app
      - /app/node_modules
    env_file:
      - ../../../../.env
    environment:
      SECRET_PATH: /be/core/gateway
    restart: unless-stopped
