name: CI/CD for Base Image

on:
  push:
    branches:
      - main
    paths:
      - 'base-images/hsm-base/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rsantamaria01
          password: ${{secrets.GHCR_PASSWORD}}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./base-images/hsm-base
          file: ./base-images/hsm-base/Dockerfile
          push: true
          tags: ghcr.io/hsm-sanosoft/hsm-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
